services:
  mongodb:
    image: mongo:5.0.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: nhatthanh
      MONGO_INITDB_ROOT_PASSWORD: Vuutruong99++
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

    # docker compose -p mongodb-software-nap up -d
